---
name: Lint
on:
  pull_request:
    type: [opened, re-opened, synchronized]
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python (latest).
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install lint dependencies.
        run: |
          sudo apt update
          sudo apt install -y make shellcheck
          sudo -H python3 -m pip install yamllint flake8
      - name: Run lint directive
        run: |
          flake8 monitor && flake8 app && flake8 daemon
          yamllint .
          shellcheck bin/*
